/*****************************************************************************\
*
*  RadeonProRenderNode constants    
*  Module Name    FireRender.h
*  Project        FireRender Engine
*
*  Description    Fire Render Interface header
*
*  Copyright 2015 Advanced Micro Devices, Inc.
*
*  All rights reserved.  This notice is intended as a precaution against
*  inadvertent publication and does not imply publication or any waiver
*  of confidentiality.  The year included in the foregoing notice is the
*  year of creation of the work.
*  @author Dmitry Kozlov (dmitry.kozlov@amd.com)
*  @author Takahiro Harada (takahiro.harada@amd.com)
*  @author Nidin Vinayakan (01@01alchemist.com)
*  @bug No known bugs.
*
\*****************************************************************************/

export const RPR_API_VERSION = 0x010000252 

/* rpr_status */
export const RPR_SUCCESS = 0 
export const RPR_ERROR_COMPUTE_API_NOT_SUPPORTED = -1 
export const RPR_ERROR_OUT_OF_SYSTEM_MEMORY = -2 
export const RPR_ERROR_OUT_OF_VIDEO_MEMORY = -3 
export const RPR_ERROR_INVALID_LIGHTPATH_EXPR = -5 
export const RPR_ERROR_INVALID_IMAGE = -6 
export const RPR_ERROR_INVALID_AA_METHOD = -7 
export const RPR_ERROR_UNSUPPORTED_IMAGE_FORMAT = -8 
export const RPR_ERROR_INVALID_GL_TEXTURE = -9 
export const RPR_ERROR_INVALID_CL_IMAGE = -10 
export const RPR_ERROR_INVALID_OBJECT = -11 
export const RPR_ERROR_INVALID_PARAMETER = -12 
export const RPR_ERROR_INVALID_TAG = -13 
export const RPR_ERROR_INVALID_LIGHT = -14 
export const RPR_ERROR_INVALID_CONTEXT = -15 
export const RPR_ERROR_UNIMPLEMENTED = -16 
export const RPR_ERROR_INVALID_API_VERSION = -17 
export const RPR_ERROR_INTERNAL_ERROR = -18 
export const RPR_ERROR_IO_ERROR = -19 
export const RPR_ERROR_UNSUPPORTED_SHADER_PARAMETER_TYPE = -20 
export const RPR_ERROR_MATERIAL_STACK_OVERFLOW = -21 
export const RPR_ERROR_INVALID_PARAMETER_TYPE = -22 
export const RPR_ERROR_UNSUPPORTED = -23 
export const RPR_ERROR_OPENCL_OUT_OF_HOST_MEMORY = -24 

/* rpr_parameter_type */
export const RPR_PARAMETER_TYPE_FLOAT = 0x1 
export const RPR_PARAMETER_TYPE_FLOAT2 = 0x2 
export const RPR_PARAMETER_TYPE_FLOAT3 = 0x3 
export const RPR_PARAMETER_TYPE_FLOAT4 = 0x4 
export const RPR_PARAMETER_TYPE_IMAGE = 0x5 
export const RPR_PARAMETER_TYPE_STRING = 0x6 
export const RPR_PARAMETER_TYPE_SHADER = 0x7 
export const RPR_PARAMETER_TYPE_UINT = 0x8 

/* rpr_image_type */
export const RPR_IMAGE_TYPE_1D = 0x1 
export const RPR_IMAGE_TYPE_2D = 0x2 
export const RPR_IMAGE_TYPE_3D = 0x3 

/* rpr_context_type */
export const RPR_CONTEXT_OPENCL = (1 << 0) 
export const RPR_CONTEXT_DIRECTCOMPUTE = (1 << 1) 
export const RPR_CONTEXT_REFERENCE = (1 << 2) 
export const RPR_CONTEXT_OPENGL = (1 << 3) 
export const RPR_CONTEXT_METAL = (1 << 4) 

/* rpr_creation_flags */
export const RPR_CREATION_FLAGS_ENABLE_GPU0 = (1 << 0) 
export const RPR_CREATION_FLAGS_ENABLE_GPU1 = (1 << 1) 
export const RPR_CREATION_FLAGS_ENABLE_GPU2 = (1 << 2) 
export const RPR_CREATION_FLAGS_ENABLE_GPU3 = (1 << 3) 
export const RPR_CREATION_FLAGS_ENABLE_CPU = (1 << 4) 
export const RPR_CREATION_FLAGS_ENABLE_GL_INTEROP = (1 << 5) 
export const RPR_CREATION_FLAGS_ENABLE_GPU4 = (1 << 6) 
export const RPR_CREATION_FLAGS_ENABLE_GPU5 = (1 << 7) 
export const RPR_CREATION_FLAGS_ENABLE_GPU6 = (1 << 8) 
export const RPR_CREATION_FLAGS_ENABLE_GPU7 = (1 << 9) 

/* rpr_aa_filter */
export const RPR_FILTER_BOX = 0x1 
export const RPR_FILTER_TRIANGLE = 0x2 
export const RPR_FILTER_GAUSSIAN = 0x3 
export const RPR_FILTER_MITCHELL = 0x4 
export const RPR_FILTER_LANCZOS = 0x5 
export const RPR_FILTER_BLACKMANHARRIS = 0x6 

/* rpr_shape_type */
export const RPR_SHAPE_TYPE_MESH = 0x1 
export const RPR_SHAPE_TYPE_INSTANCE = 0x2 

/* rpr_light_type */
export const RPR_LIGHT_TYPE_POINT = 0x1 
export const RPR_LIGHT_TYPE_DIRECTIONAL = 0x2 
export const RPR_LIGHT_TYPE_SPOT = 0x3 
export const RPR_LIGHT_TYPE_ENVIRONMENT = 0x4 
export const RPR_LIGHT_TYPE_SKY = 0x5 
export const RPR_LIGHT_TYPE_IES = 0x6 

/* rpr_object_info */
export const RPR_OBJECT_NAME = 0x777777 

/* rpr_context_info */
export const RPR_CONTEXT_CREATION_FLAGS = 0x102 
export const RPR_CONTEXT_CACHE_PATH = 0x103 
export const RPR_CONTEXT_RENDER_STATUS = 0x104 
export const RPR_CONTEXT_RENDER_STATISTICS = 0x105 
export const RPR_CONTEXT_DEVICE_COUNT = 0x106 
export const RPR_CONTEXT_PARAMETER_COUNT = 0x107 
export const RPR_CONTEXT_ACTIVE_PLUGIN = 0x108 
export const RPR_CONTEXT_SCENE = 0x109 
export const RPR_CONTEXT_AA_CELL_SIZE = 0x10A 
export const RPR_CONTEXT_AA_SAMPLES = 0x10B 
export const RPR_CONTEXT_IMAGE_FILTER_TYPE = 0x10C 
export const RPR_CONTEXT_IMAGE_FILTER_BOX_RADIUS = 0x10D 
export const RPR_CONTEXT_IMAGE_FILTER_GAUSSIAN_RADIUS = 0x10E 
export const RPR_CONTEXT_IMAGE_FILTER_TRIANGLE_RADIUS = 0x10F 
export const RPR_CONTEXT_IMAGE_FILTER_MITCHELL_RADIUS = 0x110 
export const RPR_CONTEXT_IMAGE_FILTER_LANCZOS_RADIUS = 0x111 
export const RPR_CONTEXT_IMAGE_FILTER_BLACKMANHARRIS_RADIUS = 0x112 
export const RPR_CONTEXT_TONE_MAPPING_TYPE = 0x113 
export const RPR_CONTEXT_TONE_MAPPING_LINEAR_SCALE = 0x114 
export const RPR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_SENSITIVITY = 0x115 
export const RPR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_EXPOSURE = 0x116 
export const RPR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_FSTOP = 0x117 
export const RPR_CONTEXT_TONE_MAPPING_REINHARD02_PRE_SCALE = 0x118 
export const RPR_CONTEXT_TONE_MAPPING_REINHARD02_POST_SCALE = 0x119 
export const RPR_CONTEXT_TONE_MAPPING_REINHARD02_BURN = 0x11A 
export const RPR_CONTEXT_MAX_RECURSION = 0x11B 
export const RPR_CONTEXT_RAY_CAST_EPISLON = 0x11C 
export const RPR_CONTEXT_RADIANCE_CLAMP = 0x11D 
export const RPR_CONTEXT_X_FLIP = 0x11E 
export const RPR_CONTEXT_Y_FLIP = 0x11F 
export const RPR_CONTEXT_TEXTURE_GAMMA = 0x120 
export const RPR_CONTEXT_PDF_THRESHOLD = 0x121 
export const RPR_CONTEXT_RENDER_MODE = 0x122 
export const RPR_CONTEXT_ROUGHNESS_CAP = 0x123 
export const RPR_CONTEXT_DISPLAY_GAMMA = 0x124 
export const RPR_CONTEXT_MATERIAL_STACK_SIZE = 0x125 
export const RPR_CONTEXT_CLIPPING_PLANE = 0x126 
export const RPR_CONTEXT_GPU0_NAME = 0x127 
export const RPR_CONTEXT_GPU1_NAME = 0x128 
export const RPR_CONTEXT_GPU2_NAME = 0x129 
export const RPR_CONTEXT_GPU3_NAME = 0x12A 
export const RPR_CONTEXT_CPU_NAME = 0x12B 
export const RPR_CONTEXT_GPU4_NAME = 0x12C 
export const RPR_CONTEXT_GPU5_NAME = 0x12D 
export const RPR_CONTEXT_GPU6_NAME = 0x12E 
export const RPR_CONTEXT_GPU7_NAME = 0x12F 
export const RPR_CONTEXT_TONE_MAPPING_EXPONENTIAL_INTENSITY = 0x130 
export const RPR_CONTEXT_FRAMECOUNT = 0x131 

/* last of the RPR_CONTEXT_* */
export const RPR_CONTEXT_MAX = 0x132 

/* rpr_camera_info */
export const RPR_CAMERA_TRANSFORM = 0x201 
export const RPR_CAMERA_FSTOP = 0x202 
export const RPR_CAMERA_APERTURE_BLADES = 0x203 
export const RPR_CAMERA_RESPONSE = 0x204 
export const RPR_CAMERA_EXPOSURE = 0x205 
export const RPR_CAMERA_FOCAL_LENGTH = 0x206 
export const RPR_CAMERA_SENSOR_SIZE = 0x207 
export const RPR_CAMERA_MODE = 0x208 
export const RPR_CAMERA_ORTHO_WIDTH = 0x209 
export const RPR_CAMERA_ORTHO_HEIGHT = 0x20A 
export const RPR_CAMERA_FOCUS_DISTANCE = 0x20B 
export const RPR_CAMERA_POSITION = 0x20C 
export const RPR_CAMERA_LOOKAT = 0x20D 
export const RPR_CAMERA_UP = 0x20E 
export const RPR_CAMERA_FOCAL_TILT = 0x20F 
export const RPR_CAMERA_LENS_SHIFT = 0x210 
export const RPR_CAMERA_IPD = 0x211 

/* rpr_image_info */
export const RPR_IMAGE_FORMAT = 0x301 
export const RPR_IMAGE_DESC = 0x302 
export const RPR_IMAGE_DATA = 0x303 
export const RPR_IMAGE_DATA_SIZEBYTE = 0x304 
export const RPR_IMAGE_WRAP = 0x305 

/* rpr_shape_info */
export const RPR_SHAPE_TYPE = 0x401 
export const RPR_SHAPE_VIDMEM_USAGE = 0x402 
export const RPR_SHAPE_TRANSFORM = 0x403 
export const RPR_SHAPE_MATERIAL = 0x404 
export const RPR_SHAPE_LINEAR_MOTION = 0x405 
export const RPR_SHAPE_ANGULAR_MOTION = 0x406 
export const RPR_SHAPE_VISIBILITY_FLAG = 0x407 
export const RPR_SHAPE_SHADOW_FLAG = 0x408 
export const RPR_SHAPE_SUBDIVISION_FACTOR = 0x409 
export const RPR_SHAPE_DISPLACEMENT_SCALE = 0x40A 
export const RPR_SHAPE_DISPLACEMENT_IMAGE = 0x40B 
export const RPR_SHAPE_VISIBILITY_PRIMARY_ONLY_FLAG = 0x40C 
export const RPR_SHAPE_VISIBILITY_IN_SPECULAR_FLAG = 0x40D 
export const RPR_SHAPE_SHADOW_CATCHER_FLAG = 0x40E 
export const RPR_SHAPE_VOLUME_MATERIAL = 0x40F 
export const RPR_SHAPE_OBJECT_GROUP_ID = 0x410 
export const RPR_SHAPE_SUBDIVISION_CREASEWEIGHT = 0x411 
export const RPR_SHAPE_SUBDIVISION_BOUNDARYINTEROP = 0x412 
export const RPR_SHAPE_MATERIAL_OVERRIDE = 0x413 

/* rpr_mesh_info */
export const RPR_MESH_POLYGON_COUNT = 0x501 
export const RPR_MESH_VERTEX_COUNT = 0x502 
export const RPR_MESH_NORMAL_COUNT = 0x503 
export const RPR_MESH_UV_COUNT = 0x504 
export const RPR_MESH_VERTEX_ARRAY = 0x505 
export const RPR_MESH_NORMAL_ARRAY = 0x506 
export const RPR_MESH_UV_ARRAY = 0x507 
export const RPR_MESH_VERTEX_INDEX_ARRAY = 0x508 
export const RPR_MESH_NORMAL_INDEX_ARRAY = 0x509 
export const RPR_MESH_UV_INDEX_ARRAY = 0x50A 
export const RPR_MESH_VERTEX_STRIDE = 0x50C 
export const RPR_MESH_NORMAL_STRIDE = 0x50D 
export const RPR_MESH_UV_STRIDE = 0x50E 
export const RPR_MESH_VERTEX_INDEX_STRIDE = 0x50F 
export const RPR_MESH_NORMAL_INDEX_STRIDE = 0x510 
export const RPR_MESH_UV_INDEX_STRIDE = 0x511 
export const RPR_MESH_NUM_FACE_VERTICES_ARRAY = 0x512 
export const RPR_MESH_UV2_COUNT = 0x513 
export const RPR_MESH_UV2_ARRAY = 0x514 
export const RPR_MESH_UV2_INDEX_ARRAY = 0x515 
export const RPR_MESH_UV2_STRIDE = 0x516 
export const RPR_MESH_UV2_INDEX_STRIDE = 0x517 

/* rpr_scene_info */
export const RPR_SCENE_SHAPE_COUNT = 0x701 
export const RPR_SCENE_LIGHT_COUNT = 0x702 
export const RPR_SCENE_SHAPE_LIST = 0x704 
export const RPR_SCENE_LIGHT_LIST = 0x705 
export const RPR_SCENE_CAMERA = 0x706 
export const RPR_SCENE_BACKGROUND_IMAGE = 0x708 
export const RPR_SCENE_ENVIRONMENT_OVERRIDE_REFLECTION = 0x709 
export const RPR_SCENE_ENVIRONMENT_OVERRIDE_REFRACTION = 0x70A 
export const RPR_SCENE_ENVIRONMENT_OVERRIDE_TRANSPARENCY = 0x70B 
export const RPR_SCENE_ENVIRONMENT_OVERRIDE_BACKGROUND = 0x70C 
export const RPR_SCENE_AXIS_ALIGNED_BOUNDING_BOX = 0x70D

/* rpr_light_info */
export const RPR_LIGHT_TYPE = 0x801 
export const RPR_LIGHT_TRANSFORM = 0x803 

/* rpr_light_info - point light */
export const RPR_POINT_LIGHT_RADIANT_POWER = 0x804 

/* rpr_light_info - directional light */
export const RPR_DIRECTIONAL_LIGHT_RADIANT_POWER = 0x808 
export const RPR_DIRECTIONAL_LIGHT_SHADOW_SOFTNESS = 0x809 

/* rpr_light_info - spot light */
export const RPR_SPOT_LIGHT_RADIANT_POWER = 0x80B 
export const RPR_SPOT_LIGHT_CONE_SHAPE = 0x80C 

/* rpr_light_info - environment light */
export const RPR_ENVIRONMENT_LIGHT_IMAGE = 0x80F 
export const RPR_ENVIRONMENT_LIGHT_INTENSITY_SCALE = 0x810 
export const RPR_ENVIRONMENT_LIGHT_PORTAL_LIST = 0x818 
export const RPR_ENVIRONMENT_LIGHT_PORTAL_COUNT = 0x819 

/* rpr_light_info - sky light */
export const RPR_SKY_LIGHT_TURBIDITY = 0x812 
export const RPR_SKY_LIGHT_ALBEDO = 0x813 
export const RPR_SKY_LIGHT_SCALE = 0x814 
export const RPR_SKY_LIGHT_PORTAL_LIST = 0x820 
export const RPR_SKY_LIGHT_PORTAL_COUNT = 0x821 

/* rpr_light_info - IES light */
export const RPR_IES_LIGHT_RADIANT_POWER = 0x816 
export const RPR_IES_LIGHT_IMAGE_DESC = 0x817 

/* rpr_parameter_info */
export const RPR_PARAMETER_NAME = 0x1201 
export const RPR_PARAMETER_NAME_STRING = 0x1202 
export const RPR_PARAMETER_TYPE = 0x1203 
export const RPR_PARAMETER_DESCRIPTION = 0x1204 
export const RPR_PARAMETER_VALUE = 0x1205 

/* rpr_framebuffer_info */
export const RPR_FRAMEBUFFER_FORMAT = 0x1301 
export const RPR_FRAMEBUFFER_DESC = 0x1302 
export const RPR_FRAMEBUFFER_DATA = 0x1303 
export const RPR_FRAMEBUFFER_GL_TARGET = 0x1304 
export const RPR_FRAMEBUFFER_GL_MIPLEVEL = 0x1305 
export const RPR_FRAMEBUFFER_GL_TEXTURE = 0x1306 

/* rpr_mesh_polygon_info */
export const RPR_MESH_POLYGON_VERTEX_COUNT = 0x1401 

/* rpr_mesh_polygon_vertex_info */
export const RPR_MESH_POLYGON_VERTEX_POSITION = 0x1501 
export const RPR_MESH_POLYGON_VERTEX_NORMAL = 0x1502 
export const RPR_MESH_POLYGON_VERTEX_TEXCOORD = 0x1503 

/* rpr_instance_info */
export const RPR_INSTANCE_PARENT_SHAPE = 0x1601 

/* rpr_image_format */
/* rpr_component_type */
export const RPR_COMPONENT_TYPE_UINT8 = 0x1 
export const RPR_COMPONENT_TYPE_FLOAT16 = 0x2 
export const RPR_COMPONENT_TYPE_FLOAT32 = 0x3 

/* rpr_render_mode */
export const RPR_RENDER_MODE_GLOBAL_ILLUMINATION = 0x1 
export const RPR_RENDER_MODE_DIRECT_ILLUMINATION = 0x2 
export const RPR_RENDER_MODE_DIRECT_ILLUMINATION_NO_SHADOW = 0x3 
export const RPR_RENDER_MODE_WIREFRAME = 0x4 
export const RPR_RENDER_MODE_MATERIAL_INDEX = 0x5 
export const RPR_RENDER_MODE_POSITION = 0x6 
export const RPR_RENDER_MODE_NORMAL = 0x7 
export const RPR_RENDER_MODE_TEXCOORD = 0x8 
export const RPR_RENDER_MODE_AMBIENT_OCCLUSION = 0x9 

/* rpr_camera_mode */
export const RPR_CAMERA_MODE_PERSPECTIVE = 0x1 
export const RPR_CAMERA_MODE_ORTHOGRAPHIC = 0x2 
export const RPR_CAMERA_MODE_LATITUDE_LONGITUDE_360 = 0x3 
export const RPR_CAMERA_MODE_LATITUDE_LONGITUDE_STEREO = 0x4 
export const RPR_CAMERA_MODE_CUBEMAP = 0x5 
export const RPR_CAMERA_MODE_CUBEMAP_STEREO = 0x6 

/* rpr_tonemapping_operator */
export const RPR_TONEMAPPING_OPERATOR_NONE = 0x0 
export const RPR_TONEMAPPING_OPERATOR_LINEAR = 0x1 
export const RPR_TONEMAPPING_OPERATOR_PHOTOLINEAR = 0x2 
export const RPR_TONEMAPPING_OPERATOR_AUTOLINEAR = 0x3 
export const RPR_TONEMAPPING_OPERATOR_MAXWHITE = 0x4 
export const RPR_TONEMAPPING_OPERATOR_REINHARD02 = 0x5 
export const RPR_TONEMAPPING_OPERATOR_EXPONENTIAL = 0x6 

/* rpr_volume_type */
export const RPR_VOLUME_TYPE_NONE = 0xFFFF 
export const RPR_VOLUME_TYPE_HOMOGENEOUS = 0x0 
export const RPR_VOLUME_TYPE_HETEROGENEOUS = 0x1 

/* rpr_material_node_info*/
export const RPR_MATERIAL_NODE_TYPE = 0x1101 
export const RPR_MATERIAL_NODE_SYSTEM = 0x1102 
export const RPR_MATERIAL_NODE_INPUT_COUNT = 0x1103 

/* rpr_material_node_input_info */
export const RPR_MATERIAL_NODE_INPUT_NAME = 0x1103 
export const RPR_MATERIAL_NODE_INPUT_NAME_STRING = 0x1104 
export const RPR_MATERIAL_NODE_INPUT_DESCRIPTION = 0x1105 
export const RPR_MATERIAL_NODE_INPUT_VALUE = 0x1106 
export const RPR_MATERIAL_NODE_INPUT_TYPE = 0x1107 

/* rpr_material_node_type */
export const RPR_MATERIAL_NODE_DIFFUSE = 0x1 
export const RPR_MATERIAL_NODE_MICROFACET = 0x2 
export const RPR_MATERIAL_NODE_REFLECTION = 0x3 
export const RPR_MATERIAL_NODE_REFRACTION = 0x4 
export const RPR_MATERIAL_NODE_MICROFACET_REFRACTION = 0x5 
export const RPR_MATERIAL_NODE_TRANSPARENT = 0x6 
export const RPR_MATERIAL_NODE_EMISSIVE = 0x7 
export const RPR_MATERIAL_NODE_WARD = 0x8 
export const RPR_MATERIAL_NODE_ADD = 0x9 
export const RPR_MATERIAL_NODE_BLEND = 0xA 
export const RPR_MATERIAL_NODE_ARITHMETIC = 0xB 
export const RPR_MATERIAL_NODE_FRESNEL = 0xC 
export const RPR_MATERIAL_NODE_NORMAL_MAP = 0xD 
export const RPR_MATERIAL_NODE_IMAGE_TEXTURE = 0xE 
export const RPR_MATERIAL_NODE_NOISE2D_TEXTURE = 0xF 
export const RPR_MATERIAL_NODE_DOT_TEXTURE = 0x10 
export const RPR_MATERIAL_NODE_GRADIENT_TEXTURE = 0x11 
export const RPR_MATERIAL_NODE_CHECKER_TEXTURE = 0x12 
export const RPR_MATERIAL_NODE_CONSTANT_TEXTURE = 0x13 
export const RPR_MATERIAL_NODE_INPUT_LOOKUP = 0x14 
export const RPR_MATERIAL_NODE_STANDARD = 0x15 
export const RPR_MATERIAL_NODE_BLEND_VALUE = 0x16 
export const RPR_MATERIAL_NODE_PASSTHROUGH = 0x17 
export const RPR_MATERIAL_NODE_ORENNAYAR = 0x18 
export const RPR_MATERIAL_NODE_FRESNEL_SCHLICK = 0x19 
export const RPR_MATERIAL_NODE_DIFFUSE_REFRACTION = 0x1B 
export const RPR_MATERIAL_NODE_BUMP_MAP = 0x1C 
export const RPR_MATERIAL_NODE_VOLUME = 0x1D 

/* rpr_material_node_input */
export const RPR_MATERIAL_INPUT_COLOR = 0x0 
export const RPR_MATERIAL_INPUT_COLOR0 = 0x1 
export const RPR_MATERIAL_INPUT_COLOR1 = 0x2 
export const RPR_MATERIAL_INPUT_NORMAL = 0x3 
export const RPR_MATERIAL_INPUT_UV = 0x4 
export const RPR_MATERIAL_INPUT_DATA = 0x5 
export const RPR_MATERIAL_INPUT_ROUGHNESS = 0x6 
export const RPR_MATERIAL_INPUT_IOR = 0x7 
export const RPR_MATERIAL_INPUT_ROUGHNESS_X = 0x8 
export const RPR_MATERIAL_INPUT_ROUGHNESS_Y = 0x9 
export const RPR_MATERIAL_INPUT_ROTATION = 0xA 
export const RPR_MATERIAL_INPUT_WEIGHT = 0xB 
export const RPR_MATERIAL_INPUT_OP = 0xC 
export const RPR_MATERIAL_INPUT_INVEC = 0xD 
export const RPR_MATERIAL_INPUT_UV_SCALE = 0xE 
export const RPR_MATERIAL_INPUT_VALUE = 0xF 
export const RPR_MATERIAL_INPUT_REFLECTANCE = 0x10 
export const RPR_MATERIAL_INPUT_SCALE = 0x11 
export const RPR_MATERIAL_INPUT_SCATTERING = 0x12 
export const RPR_MATERIAL_INPUT_ABSORBTION = 0x13 
export const RPR_MATERIAL_INPUT_EMISSION = 0x14 
export const RPR_MATERIAL_INPUT_G = 0x15 
export const RPR_MATERIAL_INPUT_MULTISCATTER = 0x16 
export const RPR_MATERIAL_INPUT_COLOR2 = 0x17 
export const RPR_MATERIAL_INPUT_COLOR3 = 0x18 
export const RPR_MATERIAL_INPUT_MAX = 0x19 

  
export const RPR_MATERIAL_STANDARD_INPUT_DIFFUSE_COLOR = 0x112 
export const RPR_MATERIAL_STANDARD_INPUT_DIFFUSE_NORMAL = 0x113 
export const RPR_MATERIAL_STANDARD_INPUT_GLOSSY_COLOR = 0x114 
export const RPR_MATERIAL_STANDARD_INPUT_GLOSSY_NORMAL = 0x115 
export const RPR_MATERIAL_STANDARD_INPUT_GLOSSY_ROUGHNESS_X = 0x116 
export const RPR_MATERIAL_STANDARD_INPUT_CLEARCOAT_COLOR = 0x117 
export const RPR_MATERIAL_STANDARD_INPUT_CLEARCOAT_NORMAL = 0x118 
export const RPR_MATERIAL_STANDARD_INPUT_REFRACTION_COLOR = 0x119 
export const RPR_MATERIAL_STANDARD_INPUT_REFRACTION_NORMAL = 0x11A 
export const RPR_MATERIAL_STANDARD_INPUT_REFRACTION_IOR = 0x11C 
export const RPR_MATERIAL_STANDARD_INPUT_DIFFUSE_TO_REFRACTION_WEIGHT = 0x11D 
export const RPR_MATERIAL_STANDARD_INPUT_GLOSSY_TO_DIFFUSE_WEIGHT = 0x11E 
export const RPR_MATERIAL_STANDARD_INPUT_CLEARCOAT_TO_GLOSSY_WEIGHT = 0x11F 
export const RPR_MATERIAL_STANDARD_INPUT_TRANSPARENCY = 0x120 
export const RPR_MATERIAL_STANDARD_INPUT_TRANSPARENCY_COLOR = 0x121 
export const RPR_MATERIAL_STANDARD_INPUT_REFRACTION_ROUGHNESS = 0x122 
export const RPR_MATERIAL_STANDARD_INPUT_GLOSSY_ROUGHNESS_Y = 0x123 
export const RPR_MATERIAL_INPUT_RASTER_METALLIC = 0x901 
export const RPR_MATERIAL_INPUT_RASTER_ROUGHNESS = 0x902 
export const RPR_MATERIAL_INPUT_RASTER_SUBSURFACE = 0x903 
export const RPR_MATERIAL_INPUT_RASTER_ANISOTROPIC = 0x904 
export const RPR_MATERIAL_INPUT_RASTER_SPECULAR = 0x905 
export const RPR_MATERIAL_INPUT_RASTER_SPECULARTINT = 0x906 
export const RPR_MATERIAL_INPUT_RASTER_SHEEN = 0x907 
export const RPR_MATERIAL_INPUT_RASTER_SHEENTINT = 0x908 
export const RPR_MATERIAL_INPUT_RASTER_CLEARCOAT = 0x90A 
export const RPR_MATERIAL_INPUT_RASTER_CLEARCOATGLOSS = 0x90B 
export const RPR_MATERIAL_INPUT_RASTER_COLOR = 0x90C 
export const RPR_MATERIAL_INPUT_RASTER_NORMAL = 0x90D 

/* rpr_material_node_arithmetic_operation */
export const RPR_MATERIAL_NODE_OP_ADD = 0x00 
export const RPR_MATERIAL_NODE_OP_SUB = 0x01 
export const RPR_MATERIAL_NODE_OP_MUL = 0x02 
export const RPR_MATERIAL_NODE_OP_DIV = 0x03 
export const RPR_MATERIAL_NODE_OP_SIN = 0x04 
export const RPR_MATERIAL_NODE_OP_COS = 0x05 
export const RPR_MATERIAL_NODE_OP_TAN = 0x06 
export const RPR_MATERIAL_NODE_OP_SELECT_X = 0x07 
export const RPR_MATERIAL_NODE_OP_SELECT_Y = 0x08 
export const RPR_MATERIAL_NODE_OP_SELECT_Z = 0x09 
export const RPR_MATERIAL_NODE_OP_SELECT_W = 0x0A 
export const RPR_MATERIAL_NODE_OP_COMBINE = 0x0B 
export const RPR_MATERIAL_NODE_OP_DOT3 = 0x0C 
export const RPR_MATERIAL_NODE_OP_DOT4 = 0x0D 
export const RPR_MATERIAL_NODE_OP_CROSS3 = 0x0E 
export const RPR_MATERIAL_NODE_OP_LENGTH3 = 0x0F 
export const RPR_MATERIAL_NODE_OP_NORMALIZE3 = 0x10 
export const RPR_MATERIAL_NODE_OP_POW = 0x11 
export const RPR_MATERIAL_NODE_OP_ACOS = 0x12 
export const RPR_MATERIAL_NODE_OP_ASIN = 0x13 
export const RPR_MATERIAL_NODE_OP_ATAN = 0x14 
export const RPR_MATERIAL_NODE_OP_AVERAGE_XYZ = 0x15 
export const RPR_MATERIAL_NODE_OP_AVERAGE = 0x16 
export const RPR_MATERIAL_NODE_OP_MIN = 0x17 
export const RPR_MATERIAL_NODE_OP_MAX = 0x18 
export const RPR_MATERIAL_NODE_OP_FLOOR = 0x19 
export const RPR_MATERIAL_NODE_OP_MOD = 0x1A 
export const RPR_MATERIAL_NODE_OP_ABS = 0x1B 
export const RPR_MATERIAL_NODE_OP_SHUFFLE_YZWX = 0x1C 
export const RPR_MATERIAL_NODE_OP_SHUFFLE_ZWXY = 0x1D 
export const RPR_MATERIAL_NODE_OP_SHUFFLE_WXYZ = 0x1E 
export const RPR_MATERIAL_NODE_OP_MAT_MUL = 0x1F 

/* rpr_material_node_lookup_value */
export const RPR_MATERIAL_NODE_LOOKUP_UV = 0x0 
export const RPR_MATERIAL_NODE_LOOKUP_N = 0x1 
export const RPR_MATERIAL_NODE_LOOKUP_P = 0x2 
export const RPR_MATERIAL_NODE_LOOKUP_INVEC = 0x3 
export const RPR_MATERIAL_NODE_LOOKUP_OUTVEC = 0x4 
export const RPR_MATERIAL_NODE_LOOKUP_UV1 = 0x5 

/* rpr_post_effect_info */
export const RPR_POST_EFFECT_TYPE = 0x0 
export const RPR_POST_EFFECT_PARAMETER_COUNT = 0x1 

/* rpr_post_effect_type - white balance */
export const RPR_POST_EFFECT_WHITE_BALANCE_COLOR_SPACE = 0x1 
export const RPR_POST_EFFECT_WHITE_BALANCE_COLOR_TEMPERATURE = 0x2 

/* rpr_post_effect_type - simple tonemap */
export const RPR_POST_EFFECT_SIMPLE_TONEMAP_EXPOSURE = 0x1 
export const RPR_POST_EFFECT_SIMPLE_TONEMAP_CONTRAST = 0x2 

/*rpr_aov*/
export const RPR_AOV_COLOR = 0x0 
export const RPR_AOV_OPACITY = 0x1 
export const RPR_AOV_WORLD_COORDINATE = 0x2 
export const RPR_AOV_UV = 0x3 
export const RPR_AOV_MATERIAL_IDX = 0x4 
export const RPR_AOV_GEOMETRIC_NORMAL = 0x5 
export const RPR_AOV_SHADING_NORMAL = 0x6 
export const RPR_AOV_DEPTH = 0x7 
export const RPR_AOV_OBJECT_ID = 0x8 
export const RPR_AOV_OBJECT_GROUP_ID = 0x9 
export const RPR_AOV_MAX = 0xa 

/*rpr_post_effect_type*/
export const RPR_POST_EFFECT_TONE_MAP = 0x0 
export const RPR_POST_EFFECT_WHITE_BALANCE = 0x1 
export const RPR_POST_EFFECT_SIMPLE_TONEMAP = 0x2 
export const RPR_POST_EFFECT_NORMALIZATION = 0x3 
export const RPR_POST_EFFECT_GAMMA_CORRECTION = 0x4 

/*rpr_color_space*/
export const RPR_COLOR_SPACE_SRGB = 0x1 
export const RPR_COLOR_SPACE_ADOBE_RGB = 0x2 
export const RPR_COLOR_SPACE_REC2020 = 0x3 
export const RPR_COLOR_SPACE_DCIP3 = 0x4 

/* rpr_material_node_type */
export const RPR_MATERIAL_NODE_INPUT_TYPE_FLOAT4 = 0x1 
export const RPR_MATERIAL_NODE_INPUT_TYPE_UINT = 0x2 
export const RPR_MATERIAL_NODE_INPUT_TYPE_NODE = 0x3 
export const RPR_MATERIAL_NODE_INPUT_TYPE_IMAGE = 0x4 

/* Additional Raster context properties ("raster.shadows.filter") */
export const RPR_RASTER_SHADOWS_FILTER_NONE = 0x90E
export const RPR_RASTER_SHADOWS_FILTER_PCF = 0x90F
export const RPR_RASTER_SHADOWS_FILTER_PCSS = 0x910

/* Additional Raster context properties ("raster.shadows.sampling") */
export const RPR_RASTER_SHADOWS_SAMPLING_BILINEAR = 0x911
export const RPR_RASTER_SHADOWS_SAMPLING_HAMMERSLEY = 0x912
export const RPR_RASTER_SHADOWS_SAMPLING_MULTIJITTERED = 0x913

/* rpr_subdiv_boundary_interfop_type */
export const RPR_SUBDIV_BOUNDARY_INTERFOP_TYPE_EDGE_AND_CORNER = 0x1 
export const RPR_SUBDIV_BOUNDARY_INTERFOP_TYPE_EDGE_ONLY = 0x2 

/* rpr_image_wrap_type */
export const RPR_IMAGE_WRAP_TYPE_REPEAT = 0x1 
export const RPR_IMAGE_WRAP_TYPE_MIRRORED_REPEAT = 0x2 
export const RPR_IMAGE_WRAP_TYPE_CLAMP_TO_EDGE = 0x3 
export const RPR_IMAGE_WRAP_TYPE_CLAMP_TO_BORDER = 0x4 

/* Constants */
export const RPR_MAX_AA_SAMPLES = 32 
export const RPR_MAX_AA_GRID_SIZE = 16 

/* rpr_bool */
export const RPR_FALSE = 0 
export const RPR_TRUE = 1 

/***************compatibility part***************/
export const FR_API_VERSION = 0x010000252 
export const FR_SUCCESS = 0 
export const FR_ERROR_COMPUTE_API_NOT_SUPPORTED = -1 
export const FR_ERROR_OUT_OF_SYSTEM_MEMORY = -2 
export const FR_ERROR_OUT_OF_VIDEO_MEMORY = -3 
export const FR_ERROR_INVALID_LIGHTPATH_EXPR = -5 
export const FR_ERROR_INVALID_IMAGE = -6 
export const FR_ERROR_INVALID_AA_METHOD = -7 
export const FR_ERROR_UNSUPPORTED_IMAGE_FORMAT = -8 
export const FR_ERROR_INVALID_GL_TEXTURE = -9 
export const FR_ERROR_INVALID_CL_IMAGE = -10 
export const FR_ERROR_INVALID_OBJECT = -11 
export const FR_ERROR_INVALID_PARAMETER = -12 
export const FR_ERROR_INVALID_TAG = -13 
export const FR_ERROR_INVALID_LIGHT = -14 
export const FR_ERROR_INVALID_CONTEXT = -15 
export const FR_ERROR_UNIMPLEMENTED = -16 
export const FR_ERROR_INVALID_API_VERSION = -17 
export const FR_ERROR_INTERNAL_ERROR = -18 
export const FR_ERROR_IO_ERROR = -19 
export const FR_ERROR_UNSUPPORTED_SHADER_PARAMETER_TYPE = -20 
export const FR_ERROR_MATERIAL_STACK_OVERFLOW = -21 
export const FR_ERROR_INVALID_PARAMETER_TYPE = -22 
export const FR_ERROR_UNSUPPORTED = -23 
export const FR_ERROR_OPENCL_OUT_OF_HOST_MEMORY = -24 
export const FR_PARAMETER_TYPE_FLOAT = 0x1 
export const FR_PARAMETER_TYPE_FLOAT2 = 0x2 
export const FR_PARAMETER_TYPE_FLOAT3 = 0x3 
export const FR_PARAMETER_TYPE_FLOAT4 = 0x4 
export const FR_PARAMETER_TYPE_IMAGE = 0x5 
export const FR_PARAMETER_TYPE_STRING = 0x6 
export const FR_PARAMETER_TYPE_SHADER = 0x7 
export const FR_PARAMETER_TYPE_UINT = 0x8 
export const FR_IMAGE_TYPE_1D = 0x1 
export const FR_IMAGE_TYPE_2D = 0x2 
export const FR_IMAGE_TYPE_3D = 0x3 
export const FR_CONTEXT_OPENCL = (1 << 0) 
export const FR_CONTEXT_DIRECTCOMPUTE = (1 << 1) 
export const FR_CONTEXT_REFERENCE = (1 << 2) 
export const FR_CONTEXT_OPENGL = (1 << 3) 
export const FR_CONTEXT_METAL = (1 << 4) 
export const FR_CREATION_FLAGS_ENABLE_GPU0 = (1 << 0) 
export const FR_CREATION_FLAGS_ENABLE_GPU1 = (1 << 1) 
export const FR_CREATION_FLAGS_ENABLE_GPU2 = (1 << 2) 
export const FR_CREATION_FLAGS_ENABLE_GPU3 = (1 << 3) 
export const FR_CREATION_FLAGS_ENABLE_CPU = (1 << 4) 
export const FR_CREATION_FLAGS_ENABLE_GL_INTEROP = (1 << 5) 
export const FR_CREATION_FLAGS_ENABLE_GPU4 = (1 << 6) 
export const FR_CREATION_FLAGS_ENABLE_GPU5 = (1 << 7) 
export const FR_CREATION_FLAGS_ENABLE_GPU6 = (1 << 8) 
export const FR_CREATION_FLAGS_ENABLE_GPU7 = (1 << 9) 
export const FR_FILTER_BOX = 0x1 
export const FR_FILTER_TRIANGLE = 0x2 
export const FR_FILTER_GAUSSIAN = 0x3 
export const FR_FILTER_MITCHELL = 0x4 
export const FR_FILTER_LANCZOS = 0x5 
export const FR_FILTER_BLACKMANHARRIS = 0x6 
export const FR_SHAPE_TYPE_MESH = 0x1 
export const FR_SHAPE_TYPE_INSTANCE = 0x2 
export const FR_LIGHT_TYPE_POINT = 0x1 
export const FR_LIGHT_TYPE_DIRECTIONAL = 0x2 
export const FR_LIGHT_TYPE_SPOT = 0x3 
export const FR_LIGHT_TYPE_ENVIRONMENT = 0x4 
export const FR_LIGHT_TYPE_SKY = 0x5 
export const FR_LIGHT_TYPE_IES = 0x6 
export const FR_OBJECT_NAME = 0x777777 
export const FR_CONTEXT_CREATION_FLAGS = 0x102 
export const FR_CONTEXT_CACHE_PATH = 0x103 
export const FR_CONTEXT_RENDER_STATUS = 0x104 
export const FR_CONTEXT_RENDER_STATISTICS = 0x105 
export const FR_CONTEXT_DEVICE_COUNT = 0x106 
export const FR_CONTEXT_PARAMETER_COUNT = 0x107 
export const FR_CONTEXT_ACTIVE_PLUGIN = 0x108 
export const FR_CONTEXT_SCENE = 0x109 
export const FR_CONTEXT_AA_CELL_SIZE = 0x10A 
export const FR_CONTEXT_AA_SAMPLES = 0x10B 
export const FR_CONTEXT_IMAGE_FILTER_TYPE = 0x10C 
export const FR_CONTEXT_IMAGE_FILTER_BOX_RADIUS = 0x10D 
export const FR_CONTEXT_IMAGE_FILTER_GAUSSIAN_RADIUS = 0x10E 
export const FR_CONTEXT_IMAGE_FILTER_TRIANGLE_RADIUS = 0x10F 
export const FR_CONTEXT_IMAGE_FILTER_MITCHELL_RADIUS = 0x110 
export const FR_CONTEXT_IMAGE_FILTER_LANCZOS_RADIUS = 0x111 
export const FR_CONTEXT_IMAGE_FILTER_BLACKMANHARRIS_RADIUS = 0x112 
export const FR_CONTEXT_TONE_MAPPING_TYPE = 0x113 
export const FR_CONTEXT_TONE_MAPPING_LINEAR_SCALE = 0x114 
export const FR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_SENSITIVITY = 0x115 
export const FR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_EXPOSURE = 0x116 
export const FR_CONTEXT_TONE_MAPPING_PHOTO_LINEAR_FSTOP = 0x117 
export const FR_CONTEXT_TONE_MAPPING_REINHARD02_PRE_SCALE = 0x118 
export const FR_CONTEXT_TONE_MAPPING_REINHARD02_POST_SCALE = 0x119 
export const FR_CONTEXT_TONE_MAPPING_REINHARD02_BURN = 0x11A 
export const FR_CONTEXT_MAX_RECURSION = 0x11B 
export const FR_CONTEXT_RAY_CAST_EPISLON = 0x11C 
export const FR_CONTEXT_RADIANCE_CLAMP = 0x11D 
export const FR_CONTEXT_X_FLIP = 0x11E 
export const FR_CONTEXT_Y_FLIP = 0x11F 
export const FR_CONTEXT_TEXTURE_GAMMA = 0x120 
export const FR_CONTEXT_PDF_THRESHOLD = 0x121 
export const FR_CONTEXT_RENDER_MODE = 0x122 
export const FR_CONTEXT_ROUGHNESS_CAP = 0x123 
export const FR_CONTEXT_DISPLAY_GAMMA = 0x124 
export const FR_CONTEXT_MATERIAL_STACK_SIZE = 0x125 
export const FR_CONTEXT_CLIPPING_PLANE = 0x126 
export const FR_CONTEXT_GPU0_NAME = 0x127 
export const FR_CONTEXT_GPU1_NAME = 0x128 
export const FR_CONTEXT_GPU2_NAME = 0x129 
export const FR_CONTEXT_GPU3_NAME = 0x12A 
export const FR_CONTEXT_CPU_NAME = 0x12B 
export const FR_CONTEXT_GPU4_NAME = 0x12C 
export const FR_CONTEXT_GPU5_NAME = 0x12D 
export const FR_CONTEXT_GPU6_NAME = 0x12E 
export const FR_CONTEXT_GPU7_NAME = 0x12F 
export const FR_CONTEXT_TONE_MAPPING_EXPONENTIAL_INTENSITY = 0x130 
export const FR_CONTEXT_FRAMECOUNT = 0x131 
export const FR_CONTEXT_MAX = 0x132 
export const FR_CAMERA_TRANSFORM = 0x201 
export const FR_CAMERA_FSTOP = 0x202 
export const FR_CAMERA_APERTURE_BLADES = 0x203 
export const FR_CAMERA_RESPONSE = 0x204 
export const FR_CAMERA_EXPOSURE = 0x205 
export const FR_CAMERA_FOCAL_LENGTH = 0x206 
export const FR_CAMERA_SENSOR_SIZE = 0x207 
export const FR_CAMERA_MODE = 0x208 
export const FR_CAMERA_ORTHO_WIDTH = 0x209 
export const FR_CAMERA_ORTHO_HEIGHT = 0x20A 
export const FR_CAMERA_FOCUS_DISTANCE = 0x20B 
export const FR_CAMERA_POSITION = 0x20C 
export const FR_CAMERA_LOOKAT = 0x20D 
export const FR_CAMERA_UP = 0x20E 
export const FR_CAMERA_FOCAL_TILT = 0x20F 
export const FR_CAMERA_LENS_SHIFT = 0x210 
export const FR_CAMERA_IPD = 0x211 
export const FR_IMAGE_FORMAT = 0x301 
export const FR_IMAGE_DESC = 0x302 
export const FR_IMAGE_DATA = 0x303 
export const FR_IMAGE_DATA_SIZEBYTE = 0x304 
export const FR_IMAGE_WRAP = 0x305 
export const FR_SHAPE_TYPE = 0x401 
export const FR_SHAPE_VIDMEM_USAGE = 0x402 
export const FR_SHAPE_TRANSFORM = 0x403 
export const FR_SHAPE_MATERIAL = 0x404 
export const FR_SHAPE_LINEAR_MOTION = 0x405 
export const FR_SHAPE_ANGULAR_MOTION = 0x406 
export const FR_SHAPE_VISIBILITY_FLAG = 0x407 
export const FR_SHAPE_SHADOW_FLAG = 0x408 
export const FR_SHAPE_SUBDIVISION_FACTOR = 0x409 
export const FR_SHAPE_DISPLACEMENT_SCALE = 0x40A 
export const FR_SHAPE_DISPLACEMENT_IMAGE = 0x40B 
export const FR_SHAPE_VISIBILITY_PRIMARY_ONLY_FLAG = 0x40C 
export const FR_SHAPE_VISIBILITY_IN_SPECULAR_FLAG = 0x40D 
export const FR_SHAPE_SHADOW_CATCHER_FLAG = 0x40E 
export const FR_SHAPE_VOLUME_MATERIAL = 0x40F 
export const FR_SHAPE_OBJECT_GROUP_ID = 0x410 
export const FR_SHAPE_SUBDIVISION_CREASEWEIGHT = 0x411 
export const FR_SHAPE_SUBDIVISION_BOUNDARYINTEROP = 0x412 
export const FR_SHAPE_MATERIAL_OVERRIDE = 0x413 
export const FR_MESH_POLYGON_COUNT = 0x501 
export const FR_MESH_VERTEX_COUNT = 0x502 
export const FR_MESH_NORMAL_COUNT = 0x503 
export const FR_MESH_UV_COUNT = 0x504 
export const FR_MESH_VERTEX_ARRAY = 0x505 
export const FR_MESH_NORMAL_ARRAY = 0x506 
export const FR_MESH_UV_ARRAY = 0x507 
export const FR_MESH_VERTEX_INDEX_ARRAY = 0x508 
export const FR_MESH_NORMAL_INDEX_ARRAY = 0x509 
export const FR_MESH_UV_INDEX_ARRAY = 0x50A 
export const FR_MESH_VERTEX_STRIDE = 0x50C 
export const FR_MESH_NORMAL_STRIDE = 0x50D 
export const FR_MESH_UV_STRIDE = 0x50E 
export const FR_MESH_VERTEX_INDEX_STRIDE = 0x50F 
export const FR_MESH_NORMAL_INDEX_STRIDE = 0x510 
export const FR_MESH_UV_INDEX_STRIDE = 0x511 
export const FR_MESH_NUM_FACE_VERTICES_ARRAY = 0x512 
export const FR_MESH_UV2_COUNT = 0x513 
export const FR_MESH_UV2_ARRAY = 0x514 
export const FR_MESH_UV2_INDEX_ARRAY = 0x515 
export const FR_MESH_UV2_STRIDE = 0x516 
export const FR_MESH_UV2_INDEX_STRIDE = 0x517 
export const FR_SCENE_SHAPE_COUNT = 0x701 
export const FR_SCENE_LIGHT_COUNT = 0x702 
export const FR_SCENE_SHAPE_LIST = 0x704 
export const FR_SCENE_LIGHT_LIST = 0x705 
export const FR_SCENE_CAMERA = 0x706 
export const FR_SCENE_BACKGROUND_IMAGE = 0x708 
export const FR_SCENE_ENVIRONMENT_OVERRIDE_REFLECTION = 0x709 
export const FR_SCENE_ENVIRONMENT_OVERRIDE_REFRACTION = 0x70A 
export const FR_SCENE_ENVIRONMENT_OVERRIDE_TRANSPARENCY = 0x70B 
export const FR_SCENE_ENVIRONMENT_OVERRIDE_BACKGROUND = 0x70C 
export const FR_SCENE_AXIS_ALIGNED_BOUNDING_BOX = 0x70D
export const FR_LIGHT_TYPE = 0x801 
export const FR_LIGHT_TRANSFORM = 0x803 
export const FR_POINT_LIGHT_RADIANT_POWER = 0x804 
export const FR_DIRECTIONAL_LIGHT_RADIANT_POWER = 0x808 
export const FR_DIRECTIONAL_LIGHT_SHADOW_SOFTNESS = 0x809 
export const FR_SPOT_LIGHT_RADIANT_POWER = 0x80B 
export const FR_SPOT_LIGHT_CONE_SHAPE = 0x80C 
export const FR_ENVIRONMENT_LIGHT_IMAGE = 0x80F 
export const FR_ENVIRONMENT_LIGHT_INTENSITY_SCALE = 0x810 
export const FR_ENVIRONMENT_LIGHT_PORTAL_LIST = 0x818 
export const FR_ENVIRONMENT_LIGHT_PORTAL_COUNT = 0x819 
export const FR_SKY_LIGHT_TURBIDITY = 0x812 
export const FR_SKY_LIGHT_ALBEDO = 0x813 
export const FR_SKY_LIGHT_SCALE = 0x814 
export const FR_SKY_LIGHT_PORTAL_LIST = 0x820 
export const FR_SKY_LIGHT_PORTAL_COUNT = 0x821 
export const FR_IES_LIGHT_RADIANT_POWER = 0x816 
export const FR_IES_LIGHT_IMAGE_DESC = 0x817 
export const FR_PARAMETER_NAME = 0x1201 
export const FR_PARAMETER_NAME_STRING = 0x1202 
export const FR_PARAMETER_TYPE = 0x1203 
export const FR_PARAMETER_DESCRIPTION = 0x1204 
export const FR_PARAMETER_VALUE = 0x1205 
export const FR_FRAMEBUFFER_FORMAT = 0x1301 
export const FR_FRAMEBUFFER_DESC = 0x1302 
export const FR_FRAMEBUFFER_DATA = 0x1303 
export const FR_FRAMEBUFFER_GL_TARGET = 0x1304 
export const FR_FRAMEBUFFER_GL_MIPLEVEL = 0x1305 
export const FR_FRAMEBUFFER_GL_TEXTURE = 0x1306 
export const FR_MESH_POLYGON_VERTEX_COUNT = 0x1401 
export const FR_MESH_POLYGON_VERTEX_POSITION = 0x1501 
export const FR_MESH_POLYGON_VERTEX_NORMAL = 0x1502 
export const FR_MESH_POLYGON_VERTEX_TEXCOORD = 0x1503 
export const FR_INSTANCE_PARENT_SHAPE = 0x1601 
export const FR_COMPONENT_TYPE_UINT8 = 0x1 
export const FR_COMPONENT_TYPE_FLOAT16 = 0x2 
export const FR_COMPONENT_TYPE_FLOAT32 = 0x3 
export const FR_RENDER_MODE_GLOBAL_ILLUMINATION = 0x1 
export const FR_RENDER_MODE_DIRECT_ILLUMINATION = 0x2 
export const FR_RENDER_MODE_DIRECT_ILLUMINATION_NO_SHADOW = 0x3 
export const FR_RENDER_MODE_WIREFRAME = 0x4 
export const FR_RENDER_MODE_MATERIAL_INDEX = 0x5 
export const FR_RENDER_MODE_POSITION = 0x6 
export const FR_RENDER_MODE_NORMAL = 0x7 
export const FR_RENDER_MODE_TEXCOORD = 0x8 
export const FR_RENDER_MODE_AMBIENT_OCCLUSION = 0x9 
export const FR_CAMERA_MODE_PERSPECTIVE = 0x1 
export const FR_CAMERA_MODE_ORTHOGRAPHIC = 0x2 
export const FR_CAMERA_MODE_LATITUDE_LONGITUDE_360 = 0x3 
export const FR_CAMERA_MODE_LATITUDE_LONGITUDE_STEREO = 0x4 
export const FR_CAMERA_MODE_CUBEMAP = 0x5 
export const FR_CAMERA_MODE_CUBEMAP_STEREO = 0x6 
export const FR_TONEMAPPING_OPERATOR_NONE = 0x0 
export const FR_TONEMAPPING_OPERATOR_LINEAR = 0x1 
export const FR_TONEMAPPING_OPERATOR_PHOTOLINEAR = 0x2 
export const FR_TONEMAPPING_OPERATOR_AUTOLINEAR = 0x3 
export const FR_TONEMAPPING_OPERATOR_MAXWHITE = 0x4 
export const FR_TONEMAPPING_OPERATOR_REINHARD02 = 0x5 
export const FR_TONEMAPPING_OPERATOR_EXPONENTIAL = 0x6 
export const FR_VOLUME_TYPE_NONE = 0xFFFF 
export const FR_VOLUME_TYPE_HOMOGENEOUS = 0x0 
export const FR_VOLUME_TYPE_HETEROGENEOUS = 0x1 
export const FR_MATERIAL_NODE_TYPE = 0x1101 
export const FR_MATERIAL_NODE_SYSTEM = 0x1102 
export const FR_MATERIAL_NODE_INPUT_COUNT = 0x1103 
export const FR_MATERIAL_NODE_INPUT_NAME = 0x1103 
export const FR_MATERIAL_NODE_INPUT_NAME_STRING = 0x1104 
export const FR_MATERIAL_NODE_INPUT_DESCRIPTION = 0x1105 
export const FR_MATERIAL_NODE_INPUT_VALUE = 0x1106 
export const FR_MATERIAL_NODE_INPUT_TYPE = 0x1107 
export const FR_MATERIAL_NODE_DIFFUSE = 0x1 
export const FR_MATERIAL_NODE_MICROFACET = 0x2 
export const FR_MATERIAL_NODE_REFLECTION = 0x3 
export const FR_MATERIAL_NODE_REFRACTION = 0x4 
export const FR_MATERIAL_NODE_MICROFACET_REFRACTION = 0x5 
export const FR_MATERIAL_NODE_TRANSPARENT = 0x6 
export const FR_MATERIAL_NODE_EMISSIVE = 0x7 
export const FR_MATERIAL_NODE_WARD = 0x8 
export const FR_MATERIAL_NODE_ADD = 0x9 
export const FR_MATERIAL_NODE_BLEND = 0xA 
export const FR_MATERIAL_NODE_ARITHMETIC = 0xB 
export const FR_MATERIAL_NODE_FRESNEL = 0xC 
export const FR_MATERIAL_NODE_NORMAL_MAP = 0xD 
export const FR_MATERIAL_NODE_IMAGE_TEXTURE = 0xE 
export const FR_MATERIAL_NODE_NOISE2D_TEXTURE = 0xF 
export const FR_MATERIAL_NODE_DOT_TEXTURE = 0x10 
export const FR_MATERIAL_NODE_GRADIENT_TEXTURE = 0x11 
export const FR_MATERIAL_NODE_CHECKER_TEXTURE = 0x12 
export const FR_MATERIAL_NODE_CONSTANT_TEXTURE = 0x13 
export const FR_MATERIAL_NODE_INPUT_LOOKUP = 0x14 
export const FR_MATERIAL_NODE_STANDARD = 0x15 
export const FR_MATERIAL_NODE_BLEND_VALUE = 0x16 
export const FR_MATERIAL_NODE_PASSTHROUGH = 0x17 
export const FR_MATERIAL_NODE_ORENNAYAR = 0x18 
export const FR_MATERIAL_NODE_FRESNEL_SCHLICK = 0x19 
export const FR_MATERIAL_NODE_DIFFUSE_REFRACTION = 0x1B 
export const FR_MATERIAL_NODE_BUMP_MAP = 0x1C 
export const FR_MATERIAL_NODE_VOLUME = 0x1D 
export const FR_MATERIAL_INPUT_COLOR = 0x0 
export const FR_MATERIAL_INPUT_COLOR0 = 0x1 
export const FR_MATERIAL_INPUT_COLOR1 = 0x2 
export const FR_MATERIAL_INPUT_NORMAL = 0x3 
export const FR_MATERIAL_INPUT_UV = 0x4 
export const FR_MATERIAL_INPUT_DATA = 0x5 
export const FR_MATERIAL_INPUT_ROUGHNESS = 0x6 
export const FR_MATERIAL_INPUT_IOR = 0x7 
export const FR_MATERIAL_INPUT_ROUGHNESS_X = 0x8 
export const FR_MATERIAL_INPUT_ROUGHNESS_Y = 0x9 
export const FR_MATERIAL_INPUT_ROTATION = 0xA 
export const FR_MATERIAL_INPUT_WEIGHT = 0xB 
export const FR_MATERIAL_INPUT_OP = 0xC 
export const FR_MATERIAL_INPUT_INVEC = 0xD 
export const FR_MATERIAL_INPUT_UV_SCALE = 0xE 
export const FR_MATERIAL_INPUT_VALUE = 0xF 
export const FR_MATERIAL_INPUT_REFLECTANCE = 0x10 
export const FR_MATERIAL_INPUT_SCALE = 0x11 
export const FR_MATERIAL_INPUT_SCATTERING = 0x12 
export const FR_MATERIAL_INPUT_ABSORBTION = 0x13 
export const FR_MATERIAL_INPUT_EMISSION = 0x14 
export const FR_MATERIAL_INPUT_G = 0x15 
export const FR_MATERIAL_INPUT_MULTISCATTER = 0x16 
export const FR_MATERIAL_INPUT_COLOR2 = 0x17 
export const FR_MATERIAL_INPUT_COLOR3 = 0x18 
export const FR_MATERIAL_INPUT_MAX = 0x19 
export const FR_MATERIAL_STANDARD_INPUT_DIFFUSE_COLOR = 0x112 
export const FR_MATERIAL_STANDARD_INPUT_DIFFUSE_NORMAL = 0x113 
export const FR_MATERIAL_STANDARD_INPUT_GLOSSY_COLOR = 0x114 
export const FR_MATERIAL_STANDARD_INPUT_GLOSSY_NORMAL = 0x115 
export const FR_MATERIAL_STANDARD_INPUT_GLOSSY_ROUGHNESS_X = 0x116 
export const FR_MATERIAL_STANDARD_INPUT_CLEARCOAT_COLOR = 0x117 
export const FR_MATERIAL_STANDARD_INPUT_CLEARCOAT_NORMAL = 0x118 
export const FR_MATERIAL_STANDARD_INPUT_REFRACTION_COLOR = 0x119 
export const FR_MATERIAL_STANDARD_INPUT_REFRACTION_NORMAL = 0x11A 
export const FR_MATERIAL_STANDARD_INPUT_REFRACTION_IOR = 0x11C 
export const FR_MATERIAL_STANDARD_INPUT_DIFFUSE_TO_REFRACTION_WEIGHT = 0x11D 
export const FR_MATERIAL_STANDARD_INPUT_GLOSSY_TO_DIFFUSE_WEIGHT = 0x11E 
export const FR_MATERIAL_STANDARD_INPUT_CLEARCOAT_TO_GLOSSY_WEIGHT = 0x11F 
export const FR_MATERIAL_STANDARD_INPUT_TRANSPARENCY = 0x120 
export const FR_MATERIAL_STANDARD_INPUT_TRANSPARENCY_COLOR = 0x121 
export const FR_MATERIAL_STANDARD_INPUT_REFRACTION_ROUGHNESS = 0x122 
export const FR_MATERIAL_STANDARD_INPUT_GLOSSY_ROUGHNESS_Y = 0x123 
export const FR_MATERIAL_INPUT_RASTER_METALLIC = 0x901 
export const FR_MATERIAL_INPUT_RASTER_ROUGHNESS = 0x902 
export const FR_MATERIAL_INPUT_RASTER_SUBSURFACE = 0x903 
export const FR_MATERIAL_INPUT_RASTER_ANISOTROPIC = 0x904 
export const FR_MATERIAL_INPUT_RASTER_SPECULAR = 0x905 
export const FR_MATERIAL_INPUT_RASTER_SPECULARTINT = 0x906 
export const FR_MATERIAL_INPUT_RASTER_SHEEN = 0x907 
export const FR_MATERIAL_INPUT_RASTER_SHEENTINT = 0x908 
export const FR_MATERIAL_INPUT_RASTER_CLEARCOAT = 0x90A 
export const FR_MATERIAL_INPUT_RASTER_CLEARCOATGLOSS = 0x90B 
export const FR_MATERIAL_INPUT_RASTER_COLOR = 0x90C 
export const FR_MATERIAL_INPUT_RASTER_NORMAL = 0x90D 
export const FR_MATERIAL_NODE_OP_ADD = 0x00 
export const FR_MATERIAL_NODE_OP_SUB = 0x01 
export const FR_MATERIAL_NODE_OP_MUL = 0x02 
export const FR_MATERIAL_NODE_OP_DIV = 0x03 
export const FR_MATERIAL_NODE_OP_SIN = 0x04 
export const FR_MATERIAL_NODE_OP_COS = 0x05 
export const FR_MATERIAL_NODE_OP_TAN = 0x06 
export const FR_MATERIAL_NODE_OP_SELECT_X = 0x07 
export const FR_MATERIAL_NODE_OP_SELECT_Y = 0x08 
export const FR_MATERIAL_NODE_OP_SELECT_Z = 0x09 
export const FR_MATERIAL_NODE_OP_SELECT_W = 0x0A 
export const FR_MATERIAL_NODE_OP_COMBINE = 0x0B 
export const FR_MATERIAL_NODE_OP_DOT3 = 0x0C 
export const FR_MATERIAL_NODE_OP_DOT4 = 0x0D 
export const FR_MATERIAL_NODE_OP_CROSS3 = 0x0E 
export const FR_MATERIAL_NODE_OP_LENGTH3 = 0x0F 
export const FR_MATERIAL_NODE_OP_NORMALIZE3 = 0x10 
export const FR_MATERIAL_NODE_OP_POW = 0x11 
export const FR_MATERIAL_NODE_OP_ACOS = 0x12 
export const FR_MATERIAL_NODE_OP_ASIN = 0x13 
export const FR_MATERIAL_NODE_OP_ATAN = 0x14 
export const FR_MATERIAL_NODE_OP_AVERAGE_XYZ = 0x15 
export const FR_MATERIAL_NODE_OP_AVERAGE = 0x16 
export const FR_MATERIAL_NODE_OP_MIN = 0x17 
export const FR_MATERIAL_NODE_OP_MAX = 0x18 
export const FR_MATERIAL_NODE_OP_FLOOR = 0x19 
export const FR_MATERIAL_NODE_OP_MOD = 0x1A 
export const FR_MATERIAL_NODE_OP_ABS = 0x1B 
export const FR_MATERIAL_NODE_OP_SHUFFLE_YZWX = 0x1C 
export const FR_MATERIAL_NODE_OP_SHUFFLE_ZWXY = 0x1D 
export const FR_MATERIAL_NODE_OP_SHUFFLE_WXYZ = 0x1E 
export const FR_MATERIAL_NODE_OP_MAT_MUL = 0x1F 
export const FR_MATERIAL_NODE_LOOKUP_UV = 0x0 
export const FR_MATERIAL_NODE_LOOKUP_N = 0x1 
export const FR_MATERIAL_NODE_LOOKUP_P = 0x2 
export const FR_MATERIAL_NODE_LOOKUP_INVEC = 0x3 
export const FR_MATERIAL_NODE_LOOKUP_OUTVEC = 0x4 
export const FR_MATERIAL_NODE_LOOKUP_UV1 = 0x5 
export const FR_POST_EFFECT_TYPE = 0x0 
export const FR_POST_EFFECT_PARAMETER_COUNT = 0x1 
export const FR_POST_EFFECT_WHITE_BALANCE_COLOR_SPACE = 0x1 
export const FR_POST_EFFECT_WHITE_BALANCE_COLOR_TEMPERATURE = 0x2 
export const FR_POST_EFFECT_SIMPLE_TONEMAP_EXPOSURE = 0x1 
export const FR_POST_EFFECT_SIMPLE_TONEMAP_CONTRAST = 0x2 
export const FR_AOV_COLOR = 0x0 
export const FR_AOV_OPACITY = 0x1 
export const FR_AOV_WORLD_COORDINATE = 0x2 
export const FR_AOV_UV = 0x3 
export const FR_AOV_MATERIAL_IDX = 0x4 
export const FR_AOV_GEOMETRIC_NORMAL = 0x5 
export const FR_AOV_SHADING_NORMAL = 0x6 
export const FR_AOV_DEPTH = 0x7 
export const FR_AOV_OBJECT_ID = 0x8 
export const FR_AOV_OBJECT_GROUP_ID = 0x9 
export const FR_AOV_MAX = 0xa 
export const FR_POST_EFFECT_TONE_MAP = 0x0 
export const FR_POST_EFFECT_WHITE_BALANCE = 0x1 
export const FR_POST_EFFECT_SIMPLE_TONEMAP = 0x2 
export const FR_POST_EFFECT_NORMALIZATION = 0x3 
export const FR_POST_EFFECT_GAMMA_CORRECTION = 0x4 
export const FR_COLOR_SPACE_SRGB = 0x1 
export const FR_COLOR_SPACE_ADOBE_RGB = 0x2 
export const FR_COLOR_SPACE_REC2020 = 0x3 
export const FR_COLOR_SPACE_DCIP3 = 0x4 
export const FR_MATERIAL_NODE_INPUT_TYPE_FLOAT4 = 0x1 
export const FR_MATERIAL_NODE_INPUT_TYPE_UINT = 0x2 
export const FR_MATERIAL_NODE_INPUT_TYPE_NODE = 0x3 
export const FR_MATERIAL_NODE_INPUT_TYPE_IMAGE = 0x4 
export const FR_RASTER_SHADOWS_FILTER_NONE = 0x90E
export const FR_RASTER_SHADOWS_FILTER_PCF = 0x90F
export const FR_RASTER_SHADOWS_FILTER_PCSS = 0x910
export const FR_RASTER_SHADOWS_SAMPLING_BILINEAR = 0x911
export const FR_RASTER_SHADOWS_SAMPLING_HAMMERSLEY = 0x912
export const FR_RASTER_SHADOWS_SAMPLING_MULTIJITTERED = 0x913
export const FR_SUBDIV_BOUNDARY_INTERFOP_TYPE_EDGE_AND_CORNER = 0x1 
export const FR_SUBDIV_BOUNDARY_INTERFOP_TYPE_EDGE_ONLY = 0x2 
export const FR_IMAGE_WRAP_TYPE_REPEAT = 0x1 
export const FR_IMAGE_WRAP_TYPE_MIRRORED_REPEAT = 0x2 
export const FR_IMAGE_WRAP_TYPE_CLAMP_TO_EDGE = 0x3 
export const FR_IMAGE_WRAP_TYPE_CLAMP_TO_BORDER = 0x4 
export const FR_MAX_AA_SAMPLES = 32 
export const FR_MAX_AA_GRID_SIZE = 16 
export const FR_FALSE = 0 
export const FR_TRUE = 1 
